### PR TITLE
Dependency traits

### PR DESCRIPTION
**Pull request by thoechsmann**
New exclusion rule that allows to setup dependencies between traits. Use it when one trait will require a specific other trait. For those cases it is much shorter to define compared to the exclusion rules. You can also set an option to fix the dependency instead of rejecting those configurations. This can speed up DNA generation dramatically when many dependency rules are set.

### CODE REVIEW

**Comment by thoechsmann** [comment]
has some bugs. fixing...

**Comment by thepeanutgalleryandco** [comment]
So this is effectively inclusion rules? Should we not perhaps change exclusions to filters, then have inclusions and exclusions filters?

I did start to work on inclusions...but then I was thinking about how to handle it should a specific layer item have multiple inclusions. Which one would hold true? Did you cater in your solution for this functionality?

Would you perhaps log a feature for this under issues as well please so that it is easy to link to from release notes.

Cheers for adding to the repo 😀

**Comment by thoechsmann** [comment]
It not really an inclusion, but a dependency. But yes, I agree that filters would be the better generic term for all filter rules.

**Comment by thoechsmann** [comment]
You implementation works flawlessly. Thank you. 

You have still my out-dated configuration in the config.js

**Comment by thepeanutgalleryandco** [comment]
What do you mean your "out-dated" configuration in the config.js? I have left the default config.js content from the Hashlips / CodeSTACKr repos, along with some of my additions. I then added a commented out section with all the options that someone can configure.

**Comment by thoechsmann** [comment]
E.g this in the config.js is no longer valid

```
dependendTraits: {
      autoFullfillDependency: true,
      traits:
      {
        "Eye color/Cyan": [
          "Eyeball/Red",
        ],
        "Iris/Large": [
          "Bottom lid/High",
          "Top lid/High",
        ],
      },
```

**Comment by thoechsmann** [comment]
forget my comment. I was on the wrong branch...

**Pull request closed without merging**
